### ISSUE TITLE
an exemple of database would be great

### ISSUE THREAD

**Issue by yoanmarchal** [Codefa/simple-nuxt-blog-vuetify-firebase#1]
i try to look at your exemple but without data its a bit hard

**Comment by Codefa** [comment]
> i try to look at your exemple but without data its a bit hard

You don't need a datbase ,
just put your firebase api key and firebase url then login into the admin and create a new post it will automatically create a new db items
[https://simple-nuxt-blog-vuetify-firebase.netlify.com/admin/auth](url)
visit this link just signup for a account password should be 7 characters and ee how you can make new posts

**Comment by yoanmarchal** [comment]
ok i follow your advice & it work, thanks

Another point
what rules did you use (in firebase) to prevent access

**Comment by Codefa** [comment]
> ok i follow your advice & it work, thanks
> 
> Another point
> what rules did you use (in firebase) to prevent access

### This is the Database rule 

>` {
  "rules": {
    ".read": true,
    ".write": "auth != null"
  }
}
`
it means **everyone can read/view the items of this DB but for add/update/delete user must be authenticated**

**Comment by yoanmarchal** [comment]
thanks you for your help sharon

**Comment by Codefa** [comment]
> thanks you for your help sharon

Thank you hope your issues fixed, if its = true then please cloe this issue, thank you
